= ehcache-sizeofengine

== What is this?

This library lets you size Java Object instances in bytes.

[source,java,]
----
SizeOf sizeOf = SizeOf.newInstance(); // <1>
long shallowSize = sizeOf.sizeOf(someObject); // <2>
long deepSize = sizeOf.deepSizeOf(someObject); // <3>
----
<1> Retrieves one of the multiple engines supported;
<2> Sizes `someObject` instance in bytes;
<3> Sizes `someObject` instance in bytes, as well as all objects it references.

=== The different engines

When retrieving a new `SizeOf` instance with the static `org.ehcache.sizeof.SizeOf.newInstance`, the library will try to create of
the following engines, in that order:

 . `AgentSizeOf` : Which tries to attach an agent to the JVM process and size objects using `org.ehcache.sizeof.impl.AgentLoader.instrumentation`; otherwise
 . `UnsafeSizeOf` : Which will determine Class layouts in memory using `sun.misc.Unsafe`; or finally
 . `ReflectionSizeOf` : Which will introspect Class instances and try determining object sizes that way.

Both the `ReflectionSizeOf` and the `AgentSizeOf` approach were very well covered in Dr. Heinz Kabutz's
http://www.javaspecialists.eu/archive/Issue078.html[Java Specialist Newsletter issue #78] and http://www.javaspecialists.eu/archive/Issue142.html[issue #142] respectively.
Different JVMs and their configurations may affect these sizes, see blob/master/src/main/java/org/ehcache/sizeof/impl/JvmInformation.java[JvmInformation enum] for more details.
Finally, the `UnsafeSizeOf`, we've discovered and, as far as we know, were the first ones to use.

== Avoiding sizing certain types

In some cases you want to control how far the deep sizing goes. You can do this using the `org.ehcache.sizeof.Filter` SPI.

=== Using existing filter configurators

You simply need to add the jars of the modules that you want along side this project's jar

 * Hibernate
    ** https://github.com/alexsnaps/ehcache-sizeofengine-hibernate[https://github.com/alexsnaps/ehcache-sizeofengine-hibernate v4+]
    ** https://github.com/alexsnaps/ehcache-sizeofengine-hibernate3[https://github.com/alexsnaps/ehcache-sizeofengine-hibernate3 v3+]
 * Groovy
    ** https://github.com/noamt/ehcache-sizeofengine-groovy

== Configuring the Filter yourself

In order to ignore fields or instances of certain classes when sizing object graphs, you'll have to

 . Create a http://docs.oracle.com/javase/6/docs/api/java/util/ServiceLoader.html[ServiceLoader] project, for http://terracotta-oss.github.io/ehcache-sizeofengine/apidocs/net/sf/ehcache/sizeofengine/FilterConfigurator.html[net.sf.ehcache.sizeofengine.FilterConfigurator]
   * Have your jar contain a text file named +META-INF/services/org.ehcache.sizeof.FilterConfigurator+
   * The file should contain the fully qualified class name of your implementation
 . Implement http://terracotta-oss.github.io/ehcache-sizeofengine/apidocs/net/sf/ehcache/sizeofengine/FilterConfigurator.html[FilterConfigurator]'s configure method to configure the http://terracotta-oss.github.io/ehcache-sizeofengine/apidocs/net/sf/ehcache/sizeofengine/Filter.html[Filter] of classes and fields
 . put your jar on your application's classpath, along side of the ehcache jar and this ehcache-sizeofengine jar
 . Use Ehcache's http://ehcache.org/documentation/arc[Automatic Resource Control] for your heap tier

== Example

[source,java]
----
public static final class StupidConfigurator implements FilterConfigurator {

    @Override
    public void configure(final Filter ehcacheFilter) {
        // Will not size any instance of Number, and given the second arg, no subtype neither
        ehcacheFilter.ignoreInstancesOf(Number.class, false);
    }
}
----

There can be as many +FilterConfigurator+ on the classpath as required, they'll have configure the filter once.
The +Filter+ is shared across all +SizeOfEngine+ instances created.

== Using it

=== Maven

Releases are available from Maven Central.

[source,xml]
----
<dependency>
    <groupId>org.ehcache</groupId>
    <artifactId>sizeof</artifactId>
    <version>${sizeof.version}</version>
</dependency>
----

Snapshots are available from the https://oss.sonatype.org/content/repositories/snapshots[Sonatype OSS snapshots] repository.
In order to access the snapshots, you need to add the following repository to your +pom.xml+:

[source,xml]
----
<repository>
    <id>sonatype-nexus-snapshots</id>
    <name>Sonatype Nexus Snapshots</name>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <releases>
        <enabled>false</enabled>
    </releases>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>
----
